Imports:

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm

In [46]:
df = pd.read_csv('../assets/train.csv')
del df['result']
df.iloc[:100]

,sportsObjectsAmountPer100k,sportsAmountPer100k,areasSquarePer100k,subwayDistance,pollutedPointsPercentage
0,318.0,187.0,1.201111e+06,835.506329,0.003066
1,84.0,0.0,1.699444e+05,2421.331583,0.494011
2,400.0,238.0,4.766987e+05,876.049879,0.087734
3,236.0,44.0,4.707727e+04,1763.032568,0.800674
4,448.0,273.0,5.150813e+05,1366.490654,0.091244
...,...,...,...,...,...
95,171.0,17.0,1.068602e+05,3860.441539,0.384566
96,403.0,344.0,4.644156e+05,106.933470,0.001327
97,239.0,24.0,9.496842e+04,3590.402261,0.184361
98,356.0,174.0,6.582989e+05,1108.739729,0.035316
99,64.0,19.0,1.020557e+04,4151.634296,0.893900